# Generated by Django 3.1.5 on 2021-01-17 20:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20210117_2238'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='slag',
            new_name='slug',
        ),
    ]
